[package]
name = "rust_py"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.cpython]
version = "0.7"
features = ["extension-module"]

[lib]
name = "rust_py"
crate-type = ["cdylib"]
